### ISSUE TITLE
Space tolerated in id labels

### ISSUE THREAD

**Issue by thoree** [magnusdv/quickped#1]
Great app! It's possible to produce a ped file like
![image](https://user-images.githubusercontent.com/10831495/102452791-4207fd00-403b-11eb-96ba-58d85a3f8b59.png)
which fortunately leads to
> readPed("quickped.ped")
Error: Duplicated entry in `id` vector: 1, 1

**Comment by magnusdv** [comment]
Thanks! 

I've modified QuickPed such that pedigree labels are trimmed. Hence such duplications should now be caught in the app.
