### ISSUE TITLE
Disconnected from server when adding new individuals to complex pedigree

### ISSUE THREAD

**Issue by sskiba5** [magnusdv/quickped#11]
Hello! 

This is such a fantastic tool and I am so grateful to be using it. 

I am hoping to create a pedigree that involves ~300 individuals, with various degrees of inbreeding. After ~120 entries, whenever I enter a new individual and try to update their ID name, the program quits out with the attached error. "Disconnected from the server"

![Screen Shot 2023-06-02 at 5 04 06 PM](https://github.com/magnusdv/quickped/assets/50116040/1430b1f9-bef6-4dc1-bc00-ae80ecb2b895)

Any help would be much appreciate! 

Thanks so much

**Comment by magnusdv** [comment]
Hi, I'm glad you find QuickPed useful :)

Inbred pedigrees of 300 individuals may be pushing the limits, but the disconnect sounds like a bug which should be caught. Is there a way I can reproduce the error?

**Comment by magnusdv** [comment]
Many thanks. I was able to find the error; it should be fixed in version 3.0.2 deployed now.
