### ISSUE TITLE
Carrier status is not saved in .ped file

### ISSUE THREAD

**Issue by cgimene1** [magnusdv/quickped#12]
I think it would be necessary to save the carrier status in  the .ped file

**Comment by magnusdv** [comment]
Hi,

As you say, some annotations (including carrier status) are not stored in the .ped file.

This is already documented in the [user manual](https://magnusdv.github.io/pedsuite/articles/web_only/quickped.html#ped-files), and is not likely to change any time soon, I'm afraid.

However, you might want to check out the **segregatr** package, https://github.com/magnusdv/segregatr, which enables nice plots of clinical pedigrees if you are willing to work in R.
