### ISSUE TITLE
Strange output formatting

### ISSUE THREAD

**Issue by emcarthur** [magnusdv/quickped#13]
Tried to add parents to individual 3 and output was unusual. Thanks!

![image](https://github.com/user-attachments/assets/091e0403-642b-441a-86de-203a09a48957)

![image](https://github.com/user-attachments/assets/0efc7420-0121-4181-acae-28a7c37a39f4)

**Comment by magnusdv** [comment]
Hi, unfortunately there are a few cases in which the alignment algorithm currently fails. The plot then falls back to the arrow version. 

Very often the alignment restores itself by adding a few more parents. In this case I think adding parents to individual 1 should do the trick. Not a perfect solution, but perhaps better than nothing.
