### ISSUE TITLE
Thore testing

### ISSUE THREAD

**Issue by thoree** [magnusdv/quickped#3]
* Startposisjon. 
Prøver å gjøre 1 og 2 til MZ tvillinger.
Får feilmelding, OK, men alt fjernes,
Samme hvis man prøver å lage 1 og 3 til DZ tvillinger.
Hvis man prøver å lage 1 og 2 til tvillinger, skjer ingen ting.
For få opp Trio igjen, velger jeg først et annet
pedigre og så trio.

* Jeg er usikker på hva den røde knappen
'Reset all' gjør, ingen påvirkning på
feks 'Width', men på 'Labels' (OK).

* Nevne i dokumentasjon at 'deceased' og tvillinginfo
ikke lagres i ped-filen?!

* Jeg skjønner ikke hvordan man leser inn med `readPed`
dersom det er en `aff` kolonne.
Skru av `Affection status` default?
Jeg klarer ikke å lese inn i QuickPed dersom det er en 'aff' kolonne.

**Comment by magnusdv** [comment]
Takk, tror alle disse er utbedret nå!
